# Generated by Django 4.2.4 on 2023-09-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_img", models.ImageField(upload_to="event_images/")),
                ("event_text", models.CharField(max_length=300)),
            ],
        ),
    ]
